In [155]:
import numpy as np
import pandas as pd
from numpy import genfromtxt
import math

np.seterr(divide='ignore', invalid='ignore')

data = genfromtxt('digits-training.data', delimiter=' ')
rows = np.size(data,0)
cols = np.size(data,1)


In [156]:
frdata=np.delete(data,64,1)


In [168]:
def ConvertToBin(data):
    #data=data[:,-1]
    alist = []
    for x in data:
        if x==0:
            alist.append([1,0,0,0,0,0,0,0,0,0])
        elif x==1:
            alist.append([0,1,0,0,0,0,0,0,0,0])
        elif x==2:
            alist.append([0,0,1,0,0,0,0,0,0,0])
        elif x==3:
            alist.append([0,0,0,1,0,0,0,0,0,0])
        elif x==4:
            alist.append([0,0,0,0,1,0,0,0,0,0])
        elif x==5:
            alist.append([0,0,0,0,0,1,0,0,0,0])
        elif x==6:
            alist.append([0,0,0,0,0,0,1,0,0,0])
        elif x==7:
            alist.append([0,0,0,0,0,0,0,1,0,0])
        elif x==8:
            alist.append([0,0,0,0,0,0,0,0,1,0])
        elif x==9:
            alist.append([0,0,0,0,0,0,0,0,0,1])
        else:
            pass
    finaldat = np.array(alist)
    return finaldat
    
      

def softmax(X):
    #exps = np.exp(X - np.max(X))
    #return exps / np.sum(exps)
    e = np.exp(X)
    return e / np.sum(e, axis=1, keepdims=True)

#def softmax(z):
#    z -= np.max(z)
#    sm = (np.exp(z).T / np.sum(np.exp(z), axis=0)).T
 #   return sm

def softmax_grad(s): 
    # Take the derivative of softmax element w.r.t the each logit which is usually Wi * X
    # input s is softmax value of the original input x. 
    # s.shape = (1, n) 
    # i.e. s = np.array([0.3, 0.7]), x = np.array([0, 1])

    # initialize the 2-D jacobian matrix.
    jacobian_m = np.diag(s)

    for i in range(len(jacobian_m)):
        for j in range(len(jacobian_m)):
            if i == j:
                jacobian_m[i][j] = s[i] * (1-s[i])
            else: 
                jacobian_m[i][j] = -s[i]*s[j]
    return jacobian_m


def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],15) 
        self.weights2   = np.random.rand(15,10)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = softmax(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    trim_data=frdata/16
    tr1=trim_data[0:4,:]
    X = tr1
    #y = np.array([[1,0,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,1,0,0],[0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,1,0,0,0],[0,0,1,0,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0]])
    #sp=data[:,-1][0:10]
    y= np.array(ConvertToBin(data[:,-1][0:4]))
    nn = NeuralNetwork(X,y)

    for i in range(9000):
        nn.feedforward()
        nn.backprop()

print(nn.output)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
